const DUMMY_PROJECT_ID = '33333333-3333-3333-3333-333333333333';

const DUMMY_QUEUES = [
  {
    id: 'queue-critical-01',
    projectId: DUMMY_PROJECT_ID,
    name: 'orders-critical',
    description: 'High-priority checkout orders, payment webhooks, and billing allocations',
    priority: 95,
    concurrencyLimit: 25,
    rateLimitPerSecond: 100,
    defaultTimeoutMs: 15000,
    isPaused: false,
    createdAt: new Date(Date.now() - 86400000 * 5),
    updatedAt: new Date(),
    metrics: { queued: 2, running: 1, completed: 1840, failed: 0, deadLetter: 0 },
  },
  {
    id: 'queue-email-02',
    projectId: DUMMY_PROJECT_ID,
    name: 'email-notifications',
    description: 'Transactional customer receipts, password reset links, and push notifications',
    priority: 70,
    concurrencyLimit: 15,
    rateLimitPerSecond: 50,
    defaultTimeoutMs: 20000,
    isPaused: false,
    createdAt: new Date(Date.now() - 86400000 * 4),
    updatedAt: new Date(),
    metrics: { queued: 4, running: 2, completed: 5920, failed: 1, deadLetter: 1 },
  },
  {
    id: 'queue-etl-03',
    projectId: DUMMY_PROJECT_ID,
    name: 'data-sync-etl',
    description: 'Data warehouse batch ingestions, analytical partitions, and CSV exports',
    priority: 40,
    concurrencyLimit: 5,
    rateLimitPerSecond: 10,
    defaultTimeoutMs: 60000,
    isPaused: false,
    createdAt: new Date(Date.now() - 86400000 * 3),
    updatedAt: new Date(),
    metrics: { queued: 1, running: 1, completed: 420, failed: 2, deadLetter: 2 },
  },
  {
    id: 'queue-ai-04',
    projectId: DUMMY_PROJECT_ID,
    name: 'ai-llm-pipelines',
    description: 'LLM batch prompts, embeddings generation, and vector database indexing',
    priority: 60,
    concurrencyLimit: 10,
    rateLimitPerSecond: 20,
    defaultTimeoutMs: 45000,
    isPaused: false,
    createdAt: new Date(Date.now() - 86400000 * 2),
    updatedAt: new Date(),
    metrics: { queued: 0, running: 0, completed: 890, failed: 1, deadLetter: 1 },
  },
  {
    id: 'queue-default-05',
    projectId: DUMMY_PROJECT_ID,
    name: 'default',
    description: 'Standard asynchronous background jobs and general execution',
    priority: 50,
    concurrencyLimit: 10,
    rateLimitPerSecond: 30,
    defaultTimeoutMs: 30000,
    isPaused: false,
    createdAt: new Date(Date.now() - 86400000 * 6),
    updatedAt: new Date(),
    metrics: { queued: 1, running: 0, completed: 3200, failed: 0, deadLetter: 0 },
  },
];

const DUMMY_JOBS = [
  {
    id: 'job-001-email',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-email-02',
    queueName: 'email-notifications',
    name: 'Send Order Confirmation Email',
    status: 'COMPLETED',
    priority: 80,
    attempt: 1,
    maxAttempts: 3,
    payload: { recipient: 'alex.doe@enterprise.com', orderId: 'ORD-98234-A', amount: 349.99, template: 'order_receipt' },
    output: { messageId: 'msg_982348_prod', sentAt: new Date(Date.now() - 120000).toISOString(), status: 'DELIVERED' },
    durationMs: 142,
    createdAt: new Date(Date.now() - 180000),
    startedAt: new Date(Date.now() - 121000),
    completedAt: new Date(Date.now() - 120000),
    executions: [
      { id: 'exec-01', attempt: 1, status: 'COMPLETED', durationMs: 142, workerId: 'worker-alpha-01', createdAt: new Date(Date.now() - 121000) },
    ],
    logs: [
      { level: 'INFO', message: 'Worker claimed job via SKIP LOCKED with monotonic token #10492', timestamp: new Date(Date.now() - 121000) },
      { level: 'INFO', message: 'Rendering email template: order_receipt', timestamp: new Date(Date.now() - 120500) },
      { level: 'INFO', message: 'SMTP handshake completed. Dispatching email payload.', timestamp: new Date(Date.now() - 120200) },
      { level: 'INFO', message: 'Email successfully delivered. Status: 250 OK.', timestamp: new Date(Date.now() - 120000) },
    ],
  },
  {
    id: 'job-002-stripe',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-critical-01',
    queueName: 'orders-critical',
    name: 'Process Stripe Payment Webhook charge.succeeded',
    status: 'COMPLETED',
    priority: 95,
    attempt: 1,
    maxAttempts: 3,
    idempotencyKey: 'stripe-evt-ch_3N823908234',
    payload: { eventId: 'evt_3N823908234', type: 'charge.succeeded', customer: 'cus_98234', amount: 120000, currency: 'usd' },
    output: { ledgerUpdated: true, invoiceGenerated: true, receiptUrl: 'https://pay.stripe.com/receipts/acct_8923/ch_3N' },
    durationMs: 285,
    createdAt: new Date(Date.now() - 240000),
    startedAt: new Date(Date.now() - 210000),
    completedAt: new Date(Date.now() - 209000),
    executions: [
      { id: 'exec-02', attempt: 1, status: 'COMPLETED', durationMs: 285, workerId: 'worker-beta-02', createdAt: new Date(Date.now() - 210000) },
    ],
    logs: [
      { level: 'INFO', message: 'Validating Stripe HMAC signature: pass', timestamp: new Date(Date.now() - 210000) },
      { level: 'INFO', message: 'Idempotency key locked: stripe-evt-ch_3N823908234', timestamp: new Date(Date.now() - 209800) },
      { level: 'INFO', message: 'Ledger balance incremented by $1,200.00', timestamp: new Date(Date.now() - 209200) },
      { level: 'INFO', message: 'Invoice state committed to PostgreSQL.', timestamp: new Date(Date.now() - 209000) },
    ],
  },
  {
    id: 'job-003-video',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-etl-03',
    queueName: 'data-sync-etl',
    name: 'H.264 High-Res Video Transcoding & HLS Chunking',
    status: 'RUNNING',
    priority: 60,
    attempt: 1,
    maxAttempts: 3,
    assignedWorkerId: 'worker-gamma-03',
    leaseToken: 'lease-fencing-token-891234',
    leaseUntil: new Date(Date.now() + 45000),
    payload: { sourceS3Uri: 's3://media-bucket/raw/keynote-2026.mp4', targetBitrates: ['1080p', '720p', '480p'], durationSec: 1800 },
    durationMs: null,
    createdAt: new Date(Date.now() - 30000),
    startedAt: new Date(Date.now() - 15000),
    executions: [
      { id: 'exec-03', attempt: 1, status: 'RUNNING', durationMs: null, workerId: 'worker-gamma-03', createdAt: new Date(Date.now() - 15000) },
    ],
    logs: [
      { level: 'INFO', message: 'Worker worker-gamma-03 leased job. Lease valid for 60s.', timestamp: new Date(Date.now() - 15000) },
      { level: 'INFO', message: 'Downloading source MP4 stream from S3...', timestamp: new Date(Date.now() - 12000) },
      { level: 'INFO', message: 'FFmpeg encoding stream started (Segment 14/120)', timestamp: new Date(Date.now() - 5000) },
    ],
  },
  {
    id: 'job-004-etl',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-etl-03',
    queueName: 'data-sync-etl',
    name: 'Data Warehouse Hourly Fact Table Aggregation',
    status: 'QUEUED',
    priority: 50,
    attempt: 0,
    maxAttempts: 3,
    payload: { partition: '2026-08-23-H19', recordsToProcess: 450000, targetWarehouse: 'snowflake' },
    createdAt: new Date(Date.now() - 8000),
    runAt: new Date(),
    executions: [],
    logs: [
      { level: 'INFO', message: 'Job enqueued via Cron Schedule: Hourly Fact Table Aggregation', timestamp: new Date(Date.now() - 8000) },
    ],
  },
  {
    id: 'job-005-timeout',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-etl-03',
    queueName: 'data-sync-etl',
    name: 'Sync 50,000 Product Inventory SKUs (Timeout Case)',
    status: 'DEAD_LETTER',
    priority: 70,
    attempt: 3,
    maxAttempts: 3,
    timeoutMs: 15000,
    payload: { vendorId: 'vnd_supplier_global', skuCount: 50000, syncMode: 'FULL_REPLACE' },
    error: 'ETIMEDOUT: Job execution exceeded 15000ms timeout deadline before SQL commit',
    createdAt: new Date(Date.now() - 3600000),
    startedAt: new Date(Date.now() - 3500000),
    completedAt: new Date(Date.now() - 3485000),
    executions: [
      {
        id: 'exec-05-3',
        attempt: 3,
        status: 'FAILED',
        durationMs: 15002,
        workerId: 'worker-alpha-01',
        error: 'ETIMEDOUT: Connection pool request exceeded 15000ms deadline',
        stackTrace: 'Error: Query timeout at PgPool.query (node_modules/pg-pool/index.js:342:11)\n    at InventorySyncHandler.execute (src/handlers/inventory.ts:89:15)\n    at WorkerEngine.processJob (src/worker.engine.ts:245:9)',
        createdAt: new Date(Date.now() - 3500000),
      },
    ],
    logs: [
      { level: 'INFO', message: 'Execution attempt 3 started on worker-alpha-01', timestamp: new Date(Date.now() - 3500000) },
      { level: 'WARN', message: 'Querying external ERP catalog API...', timestamp: new Date(Date.now() - 3495000) },
      { level: 'ERROR', message: 'Watchdog aborted task: execution duration exceeded timeoutMs limit (15000ms)', timestamp: new Date(Date.now() - 3485000) },
      { level: 'WARN', message: 'Maximum attempts (3/3) exhausted. Moving job to Dead Letter Queue.', timestamp: new Date(Date.now() - 3485000) },
    ],
  },
  {
    id: 'job-006-rate-limit',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-ai-04',
    queueName: 'ai-llm-pipelines',
    name: 'OpenAI GPT-4 Batch Translation Pipeline (429 Rate Limit)',
    status: 'DEAD_LETTER',
    priority: 65,
    attempt: 3,
    maxAttempts: 3,
    payload: { sourceLang: 'en', targetLang: 'de', batchSize: 200, model: 'gpt-4o' },
    error: 'HTTP 429: Rate limit exceeded for organization. Too Many Requests. Retry-After: 30',
    createdAt: new Date(Date.now() - 1800000),
    startedAt: new Date(Date.now() - 1700000),
    completedAt: new Date(Date.now() - 1698000),
    executions: [
      {
        id: 'exec-06-3',
        attempt: 3,
        status: 'FAILED',
        durationMs: 840,
        workerId: 'worker-beta-02',
        error: 'HTTP 429 Too Many Requests',
        stackTrace: 'AxiosError: Request failed with status code 429\n    at settle (node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:599:11)\n    at OpenAiHandler.translateBatch (src/handlers/openai.ts:45:7)',
        createdAt: new Date(Date.now() - 1700000),
      },
    ],
    logs: [
      { level: 'INFO', message: 'Dispatching batch prompt of 200 items to OpenAI endpoint', timestamp: new Date(Date.now() - 1700000) },
      { level: 'ERROR', message: 'Upstream HTTP Error 429: Rate limit quota exceeded.', timestamp: new Date(Date.now() - 1698000) },
      { level: 'WARN', message: 'Max retries exhausted. Archived to DLQ for rate-limit tuning.', timestamp: new Date(Date.now() - 1698000) },
    ],
  },
  {
    id: 'job-007-upstream',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-email-02',
    queueName: 'email-notifications',
    name: 'Send SMS Notification via Twilio Gateway (Upstream 503)',
    status: 'DEAD_LETTER',
    priority: 85,
    attempt: 3,
    maxAttempts: 3,
    payload: { phone: '+14155552671', text: 'Your 2FA security code is 982134', provider: 'twilio' },
    error: 'HTTP 503: Service Unavailable - Downstream upstream gateway timeout',
    createdAt: new Date(Date.now() - 900000),
    startedAt: new Date(Date.now() - 850000),
    completedAt: new Date(Date.now() - 848000),
    executions: [
      {
        id: 'exec-07-3',
        attempt: 3,
        status: 'FAILED',
        durationMs: 1200,
        workerId: 'worker-alpha-01',
        error: 'HTTP 503 Bad Gateway',
        stackTrace: 'GatewayError: 503 Bad Gateway from https://api.twilio.com/2010-04-01/Accounts/AC/Messages.json\n    at TwilioClient.sendSms (src/services/twilio.ts:32:11)\n    at SmsHandler.execute (src/handlers/sms.ts:18:5)',
        createdAt: new Date(Date.now() - 850000),
      },
    ],
    logs: [
      { level: 'INFO', message: 'Executing SMS delivery attempt 3/3', timestamp: new Date(Date.now() - 850000) },
      { level: 'ERROR', message: 'Twilio edge server returned HTTP 503 Service Unavailable', timestamp: new Date(Date.now() - 848000) },
      { level: 'WARN', message: 'Max attempts reached. Job preserved in Dead Letter Queue.', timestamp: new Date(Date.now() - 848000) },
    ],
  },
  {
    id: 'job-008-oom',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-etl-03',
    queueName: 'data-sync-etl',
    name: 'In-Memory 500MB CSV Report Generation (OOM Crash)',
    status: 'DEAD_LETTER',
    priority: 45,
    attempt: 3,
    maxAttempts: 3,
    payload: { format: 'csv', rowCount: 1500000, memoryMode: 'BUFFER_ALL' },
    error: 'FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory',
    createdAt: new Date(Date.now() - 5400000),
    startedAt: new Date(Date.now() - 5300000),
    completedAt: new Date(Date.now() - 5290000),
    executions: [
      {
        id: 'exec-08-3',
        attempt: 3,
        status: 'FAILED',
        durationMs: 4500,
        workerId: 'worker-gamma-03',
        error: 'V8 Out of Memory Error',
        stackTrace: 'RangeError: Array buffer allocation failed\n    at new ArrayBuffer (<anonymous>)\n    at CsvExporter.bufferRows (src/handlers/csv.ts:102:18)\n    at WorkerEngine.run (src/worker.engine.ts:180:9)',
        createdAt: new Date(Date.now() - 5300000),
      },
    ],
    logs: [
      { level: 'INFO', message: 'Allocating 1.5 million rows into memory buffer...', timestamp: new Date(Date.now() - 5300000) },
      { level: 'ERROR', message: 'V8 Heap Memory Limit Exceeded (1420MB/1420MB)', timestamp: new Date(Date.now() - 5290000) },
    ],
  },
  {
    id: 'job-009-json',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-default-05',
    queueName: 'default',
    name: 'Parse Ingestion Webhook Body (Malformed JSON Payload)',
    status: 'DEAD_LETTER',
    priority: 50,
    attempt: 3,
    maxAttempts: 3,
    payload: { rawString: '<html><body>502 Bad Gateway</body></html>', contentType: 'application/json' },
    error: 'SyntaxError: Unexpected token < in JSON at position 0',
    createdAt: new Date(Date.now() - 7200000),
    startedAt: new Date(Date.now() - 7100000),
    completedAt: new Date(Date.now() - 7099000),
    executions: [
      {
        id: 'exec-09-3',
        attempt: 3,
        status: 'FAILED',
        durationMs: 15,
        workerId: 'worker-alpha-01',
        error: 'SyntaxError: Unexpected token < in JSON at position 0',
        stackTrace: 'SyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at WebhookParser.execute (src/handlers/webhook.ts:24:19)',
        createdAt: new Date(Date.now() - 7100000),
      },
    ],
    logs: [
      { level: 'ERROR', message: 'JSON.parse failed on unparseable HTML error page string', timestamp: new Date(Date.now() - 7099000) },
    ],
  },
  {
    id: 'job-010-payroll',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-critical-01',
    queueName: 'orders-critical',
    name: 'Disburse Employee Payroll Direct Deposit',
    status: 'COMPLETED',
    priority: 98,
    attempt: 1,
    maxAttempts: 3,
    idempotencyKey: 'payroll-batch-2026-08',
    payload: { batchMonth: '2026-08', totalDisbursed: 458920.00, employeeCount: 142, bankRouting: 'ACH_NACHA' },
    output: { achFileGenerated: true, federalReserveAck: 'ACH-ACK-89213', status: 'SETTLED' },
    durationMs: 412,
    createdAt: new Date(Date.now() - 600000),
    startedAt: new Date(Date.now() - 590000),
    completedAt: new Date(Date.now() - 589000),
    executions: [
      { id: 'exec-10', attempt: 1, status: 'COMPLETED', durationMs: 412, workerId: 'worker-beta-02', createdAt: new Date(Date.now() - 590000) },
    ],
    logs: [
      { level: 'INFO', message: 'Validating NACHA ACH formatting for 142 employee bank accounts', timestamp: new Date(Date.now() - 590000) },
      { level: 'INFO', message: 'Bank wire batch dispatched. Total: $458,920.00', timestamp: new Date(Date.now() - 589000) },
    ],
  },
  {
    id: 'job-011-cancelled',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-default-05',
    queueName: 'default',
    name: 'Nightly Database Index Defragmentation Run',
    status: 'CANCELLED',
    priority: 30,
    attempt: 0,
    maxAttempts: 1,
    payload: { tableScope: 'ALL_INDEXES', concurrent: true },
    error: 'Cancelled by operator: scheduled maintenance window overlapping with active deployment',
    createdAt: new Date(Date.now() - 1200000),
    completedAt: new Date(Date.now() - 1100000),
    executions: [],
    logs: [
      { level: 'WARN', message: 'Operator issued job cancellation with reason: scheduled maintenance window overlapping', timestamp: new Date(Date.now() - 1100000) },
    ],
  },
];

const DUMMY_WORKERS = [
  {
    id: 'worker-alpha-01',
    name: 'Worker Alpha (General Execution)',
    status: 'ACTIVE',
    concurrency: 15,
    runningCount: 1,
    lastHeartbeat: new Date(),
    queues: [
      { queue: { id: 'queue-critical-01', name: 'orders-critical' } },
      { queue: { id: 'queue-email-02', name: 'email-notifications' } },
      { queue: { id: 'queue-default-05', name: 'default' } },
    ],
  },
  {
    id: 'worker-beta-02',
    name: 'Worker Beta (High-Priority Orders)',
    status: 'ACTIVE',
    concurrency: 20,
    runningCount: 0,
    lastHeartbeat: new Date(),
    queues: [
      { queue: { id: 'queue-critical-01', name: 'orders-critical' } },
      { queue: { id: 'queue-ai-04', name: 'ai-llm-pipelines' } },
    ],
  },
  {
    id: 'worker-gamma-03',
    name: 'Worker Gamma (ETL & Video Heavy)',
    status: 'ACTIVE',
    concurrency: 10,
    runningCount: 1,
    lastHeartbeat: new Date(),
    queues: [
      { queue: { id: 'queue-etl-03', name: 'data-sync-etl' } },
    ],
  },
];

const DUMMY_BATCHES = [
  {
    id: 'batch-01-payroll',
    projectId: DUMMY_PROJECT_ID,
    name: 'Monthly Payroll & Tax Settlement Batch',
    status: 'COMPLETED',
    totalJobs: 10,
    completedJobs: 10,
    failedJobs: 0,
    onCompleteWebhook: 'https://api.internal/payroll/callback',
    createdAt: new Date(Date.now() - 3600000 * 2),
    updatedAt: new Date(Date.now() - 3600000),
    jobs: [
      { id: 'b-job-1', name: 'Calculate State Tax Withholdings', status: 'COMPLETED', priority: 90 },
      { id: 'b-job-2', name: 'Calculate Federal FICA Withholdings', status: 'COMPLETED', priority: 90 },
      { id: 'b-job-3', name: 'Generate ACH Direct Deposit Directives', status: 'COMPLETED', priority: 90 },
      { id: 'b-job-4', name: 'Disburse Payroll Wire', status: 'COMPLETED', priority: 95 },
      { id: 'b-job-5', name: 'Email Salary Payslips to 142 Staff', status: 'COMPLETED', priority: 80 },
    ],
  },
  {
    id: 'batch-02-catalog',
    projectId: DUMMY_PROJECT_ID,
    name: 'Black Friday Product Catalog Global Sync',
    status: 'IN_PROGRESS',
    totalJobs: 8,
    completedJobs: 5,
    failedJobs: 1,
    onCompleteWebhook: 'https://api.internal/catalog/callback',
    createdAt: new Date(Date.now() - 1800000),
    updatedAt: new Date(),
    jobs: [
      { id: 'b-job-6', name: 'Sync Electronics Category (US-East)', status: 'COMPLETED', priority: 70 },
      { id: 'b-job-7', name: 'Sync Fashion & Apparel Category', status: 'COMPLETED', priority: 70 },
      { id: 'b-job-8', name: 'Sync Home & Kitchen Category', status: 'FAILED', priority: 70 },
      { id: 'b-job-9', name: 'Rebuild OpenSearch Index Shard #1', status: 'COMPLETED', priority: 60 },
      { id: 'b-job-10', name: 'Rebuild OpenSearch Index Shard #2', status: 'RUNNING', priority: 60 },
    ],
  },
];

const DUMMY_SCHEDULES = [
  {
    id: 'sched-01-nightly',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-etl-03',
    name: 'Nightly Data Warehouse Fact Table Aggregation',
    cronExpression: '0 0 * * *',
    timezone: 'UTC',
    status: 'ACTIVE',
    priority: 50,
    totalRuns: 142,
    lastRunAt: new Date(Date.now() - 86400000),
    nextRunAt: new Date(Date.now() + 14400000),
    createdAt: new Date(Date.now() - 86400000 * 30),
  },
  {
    id: 'sched-02-hourly-health',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-default-05',
    name: 'Hourly Cluster Deep Health Probe & Lease Sweeper',
    cronExpression: '0 * * * *',
    timezone: 'UTC',
    status: 'ACTIVE',
    priority: 75,
    totalRuns: 720,
    lastRunAt: new Date(Date.now() - 1800000),
    nextRunAt: new Date(Date.now() + 1800000),
    createdAt: new Date(Date.now() - 86400000 * 30),
  },
  {
    id: 'sched-03-cache-warmup',
    projectId: DUMMY_PROJECT_ID,
    queueId: 'queue-critical-01',
    name: '5-Minute Redis Cache Pre-warming for Flash Deals',
    cronExpression: '*/5 * * * *',
    timezone: 'UTC',
    status: 'ACTIVE',
    priority: 90,
    totalRuns: 8640,
    lastRunAt: new Date(Date.now() - 120000),
    nextRunAt: new Date(Date.now() + 180000),
    createdAt: new Date(Date.now() - 86400000 * 30),
  },
];

const DUMMY_CHAOS_TIMELINE = [
  {
    id: 'chaos-01',
    type: 'LEASE_EXPIRED_SIMULATED',
    description: 'Artificially backdated lease expiration for Job [job-003-video] (30s in past)',
    targetId: 'job-003-video',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    details: { simulatedLeaseUntil: new Date(Date.now() - 150000).toISOString() },
  },
  {
    id: 'chaos-02',
    type: 'SWEEPER_TRIGGERED',
    description: 'Executed on-demand lease recovery sweep. Reclaimed 1 stale job lease.',
    targetId: 'scheduler-sweeper',
    timestamp: new Date(Date.now() - 90000).toISOString(),
    details: { recoveredCount: 1, jobIds: ['job-003-video'] },
  },
  {
    id: 'chaos-03',
    type: 'JOB_FAILED_SIMULATED',
    description: 'Forced unhandled runtime exception on Job [job-007-upstream] (Archived to DLQ)',
    targetId: 'job-007-upstream',
    timestamp: new Date(Date.now() - 60000).toISOString(),
    details: { reason: 'HTTP 503 Bad Gateway', isDeadLetter: true },
  },
];

module.exports = {
  DUMMY_PROJECT_ID,
  DUMMY_QUEUES,
  DUMMY_JOBS,
  DUMMY_WORKERS,
  DUMMY_BATCHES,
  DUMMY_SCHEDULES,
  DUMMY_CHAOS_TIMELINE,
};
